algorithm:
  alpha: 0.2
  class: OracleSAC
checkpoint: null
dataloader:
  batch_size: null
  num_workers: 2
dataset:
- batch_size: 256
  class: RPLOfflineDataset
  env: HalfCheetah-v3
  variant: gravity-100
debug: false
device: null
env: HalfCheetah-v3
env_kwargs: null
env_wrapper: MujocoParamOverWrite
env_wrapper_kwargs:
  do_scale: true
  overwrite_args:
    gravity: 1.0
eval:
  deterministic: true
  function: eval_offline
  num_ep: 10
gravity: 1.0
name: default
network:
  actor:
    class: SquashedGaussianActor
    hidden_dims:
    - 256
    - 256
  critic:
    class: Critic
    ensemble_size: 2
    hidden_dims:
    - 256
    - 256
optim:
  default:
    class: Adam
    lr: 0.0003
processor: null
schedulers:
  actor:
    T_max: 500000
    class: CosineAnnealingLR
seed: 0
trainer:
  env_freq: null
  eval_freq: 5000
  log_freq: 500
  profile_freq: 500
  total_steps: 1000000
variant: gravity-100
wandb:
  activate: false
  entity: null
  project: null
