algorithm:
  class: OracleSAC
  alpha: 0.2
  auto_alpha: false

checkpoint: null
seed: 0
name: default
debug: false
device: null
wandb:
  activate: false
  entity: null
  project: null

gravity: 1.0
variant: gravity-100

env: HalfCheetah-v3
env_kwargs:
env_wrapper: MujocoParamOverWrite
env_wrapper_kwargs:
  overwrite_args:
    gravity: <gravity>
  do_scale: True

optim:
  default:
    class: Adam
    lr: 0.0003

network:
  actor:
    class: SquashedGaussianActor
    hidden_dims: [256, 256]
  critic:
    class: Critic
    ensemble_size: 2
    hidden_dims: [256, 256]
  
buffer:
  max_buffer_size: 100000
  batch_size: 256

trainer:
  random_policy_step: 1000 #5000
  warmup_step: 2000
  max_trajectory_length: 1000
  env_freq: null
  total_steps: 1000000
  log_freq: 500
  profile_freq: 500
  eval_freq: 5000

eval:
  function: eval_offline
  num_ep: 10
  deterministic: true

schedulers:
  actor:
    class: CosineAnnealingLR
    T_max: 500000

processor: null
