algorithm:
  class: MultiSpatialRewardModelLearning
  num_preference: 1
  preference_dimension: 32
  embed_type: Test

checkpoint: null
seed: 0
name: default
debug: false
device: null
wandb:
  activate: false
  entity: null
  project: null

embedding:
  HIM:
    embed_args:
      seq_len: 100
      znorm_loss_ratio: 0.1
      warmup_steps: 10000
    network:
      encoder:
        embed_dim: 128
        num_layers: 3
        num_heads: 2
        dropout: 0.1
      reconstructor:
        embed_dim: 128
        num_layers: 3
        num_heads: 1
        dropout: 0.1
    optim:
      encoder:
        class: AdamW
        lr: 0.0001
        weight_decay: 0.0001
      reconstructor:
        class: AdamW
        lr: 0.0001
        weight_decay: 0.0001
    schedulers:
    processor: null
    checkpoint: null
  BT:
    embed_args:
      type: Linear
    network:
      encoder:
        class: EnsembleMLP
        ensemble_size: 1
        hidden_dims: [256, 256]
        activation: identity
    optim:
      encoder:
        class: Adam
        lr: 0.0003
    schedulers:
    processor: null
    checkpoint: null
  SALE:
    embed_args:
      type: Linear
    network:
      state_encoder:
        class: EnsembleMLP
        ensemble_size: 1
        hidden_dims: [256, 256]
        activation: ELU
      joint_encoder:
        class: EnsembleMLP
        ensemble_size: 1
        hidden_dims: [256, 256]
        activation: identity
    optim:
      state_encoder:
        class: Adam
        lr: 0.0003
      joint_encoder:
        class: Adam
        lr: 0.0003
    schedulers:
    processor: null
    checkpoint: null
  Test:
    embed_args:
      bt_ratio: 0.5
      sale_ratio: 1
    network:
      state_encoder:
        class: EnsembleMLP
        ensemble_size: 1
        hidden_dims: [256, 256]
        activation: ELU
      joint_encoder:
        class: EnsembleMLP
        ensemble_size: 1
        hidden_dims: [256, 256]
        activation: identity
    optim:
      state_encoder:
        class: Adam
        lr: 0.0005
      joint_encoder:
        class: Adam
        lr: 0.0005
    schedulers:
    processor: null
    checkpoint: null
  
  

env: hopper-medium-expert-v2
env_kwargs:
env_wrapper:
env_wrapper_kwargs:

optim:
  default:
    class: Adam
    lr: 0.0003

network:


rm_dataset:
  BT:
    - class: D4RLOfflineDataset
      env: hopper-medium-replay-v2
      batch_size: 128
      mode: trajectory
  SALE:
    - class: IPLComparisonOfflineDataset
      env: hopper-medium-replay-v2
      batch_size: 128
      mode: script
  HIM:
    - class: OPPODataset
      env: hopper-medium-replay-v2
      batch_size: 128 # [64, 128]
      seq_len: 100
      foresee: 200
  Test:
    - class: IPLComparisonOfflineDataset
      env: hopper-medium-replay-v2
      batch_size: 256
      mode: script

rm_dataloader:
  num_workers: 2
  batch_size: null

rl_dataset:
  - class: D4RLOfflineDataset
    env: hopper-medium-replay-v2
    batch_size: 512
    mode: transition

rl_dataloader:
  num_workers: 2
  batch_size: null

trainer:
  env_freq: null
  rm_label: true
  embed_steps: 50
  cluster_steps: 0
  rl_steps: 1
  log_freq: 500
  profile_freq: 500
  eval_freq: 5000   # don't do eval

rm_eval:

rl_eval:

schedulers:

processor: null
