algorithm: IPL_IQL
algorithm_kwargs:
  beta: 0.3333
  expectile: 0.7
  reward_reg: 0.5
  reg_replay_weight: 0.5
  actor_replay_weight: 0.5
  value_replay_weight: 0.5
  tau: 0.005
  max_exp_clip: 100.0
  discount: 0.99
  target_freq: 1

checkpoint: null
seed: 0
name: state_dense
debug: false
device: null
wandb:
  activate: false
  entity: null
  project: null

env: mw_drawer-open-v2
env_kwargs:
env_wrapper:
env_wrapper_kwargs:

optim:
  default:
    class: Adam
    kwargs:
      lr: 0.0003

network:
  actor:
    class: SquashedDeterministicActor
    kwargs:
      dropout: 0.25
      hidden_dims: [512, 512]
  critic:
    class: Critic
    kwargs:
      ensemble_size: 2
      hidden_dims: [512, 512]
  value:
    class: Critic
    kwargs:
      ensemble_size: 1
      hidden_dims: [512, 512]

dataset:
  - class: MetaworldComparisonOfflineDataset
    kwargs:
      env: mw_drawer-open-v2
      label_key: rl_sum
      segment_length: null
      batch_size: 96
      capacity: 2500
      mode: dense  # Choices: {sparse, dense}
      discount: 0.99

dataloader:
  num_workers: 0  # use the main thread to sample data
  batch_size: null  # do not merge the data along batch axis

trainer:
  env_freq: null
  total_steps: 1000000
  log_freq: 500
  profile_freq: 500
  eval_freq: 5000

eval:
  function: eval_offline
  kwargs:
    num_ep: 10
    deterministic: true

schedulers:

processor: null
